import { Conversation, Store } from './types'

export const mockStores: Store[] = [
  { id: 'store-1', name: 'TechGear SG', channel: 'telegram', unreadCount: 4 },
  { id: 'store-2', name: 'HomeDecor MY', channel: 'telegram', unreadCount: 2 },
]

const now = new Date()
const minsAgo = (m: number) => new Date(now.getTime() - m * 60000)
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000)
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000)

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-1',
    storeName: 'TechGear SG',
    externalId: 'tg-101',
    sender: { name: 'Wei Ling Tan' },
    lastMessage: 'Hi, I ordered the wireless earbuds 3 days ago but haven\'t received any shipping update?',
    lastMessageAt: minsAgo(3),
    isRead: false,
    tags: ['shipping'],
    assignedTo: 'You',
    aiSuggestion: {
      text: 'Hi Wei Ling! Your order #TG-88421 was dispatched on 8 May via J&T Express. Tracking number: JT0123456789. Estimated delivery is 10–12 May. You can track it at jtexpress.sg. Let me know if you need anything else!',
      confidence: 'high',
      autoSent: false,
    },
    order: {
      id: 'TG-88421',
      status: 'Shipped',
      items: 'Sony WF-1000XM5 Earbuds x1',
      total: 'SGD 289.00',
      trackingNumber: 'JT0123456789',
    },
    messages: [
      {
        id: 'msg-1-1',
        conversationId: 'conv-1',
        sender: 'buyer',
        content: 'Hello, I placed an order for the wireless earbuds on 7 May.',
        timestamp: hoursAgo(5),
      },
      {
        id: 'msg-1-2',
        conversationId: 'conv-1',
        sender: 'agent',
        content: 'Hi Wei Ling! Thanks for your order. Let me check the status for you.',
        timestamp: hoursAgo(4),
      },
      {
        id: 'msg-1-3',
        conversationId: 'conv-1',
        sender: 'buyer',
        content: 'Hi, I ordered the wireless earbuds 3 days ago but haven\'t received any shipping update?',
        timestamp: minsAgo(3),
      },
    ],
  },
  {
    id: 'conv-2',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-1',
    storeName: 'TechGear SG',
    externalId: 'tg-102',
    sender: { name: 'Ahmad Faizal' },
    lastMessage: 'Boleh tak refund? Barang rosak masa sampai',
    lastMessageAt: minsAgo(18),
    isRead: false,
    tags: ['return', 'damaged'],
    aiSuggestion: {
      text: 'Hi Ahmad, saya minta maaf sebab barang sampai dalam keadaan rosak. Boleh hantarkan gambar barang yang rosak tu? Kami akan proses refund atau penggantian dalam masa 24 jam. Terima kasih atas kesabaran anda.',
      confidence: 'medium',
      autoSent: false,
    },
    order: {
      id: 'TG-88389',
      status: 'Delivered',
      items: 'Mechanical Keyboard TKL x1',
      total: 'SGD 149.00',
    },
    messages: [
      {
        id: 'msg-2-1',
        conversationId: 'conv-2',
        sender: 'buyer',
        content: 'Saya terima barang tadi tapi kotak dah kemek.',
        timestamp: hoursAgo(2),
      },
      {
        id: 'msg-2-2',
        conversationId: 'conv-2',
        sender: 'buyer',
        content: 'Boleh tak refund? Barang rosak masa sampai',
        timestamp: minsAgo(18),
      },
    ],
  },
  {
    id: 'conv-3',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-2',
    storeName: 'HomeDecor MY',
    externalId: 'tg-201',
    sender: { name: 'Priya Nair' },
    lastMessage: 'Does this lamp come in white? I only see beige on the listing',
    lastMessageAt: minsAgo(42),
    isRead: false,
    tags: ['product-query'],
    aiSuggestion: {
      text: 'Hi Priya! The Scandinavian Table Lamp is currently available in Beige and Oak only. We\'re expecting a White variant in late June — would you like me to notify you when it\'s in stock?',
      confidence: 'high',
      autoSent: false,
    },
    order: undefined,
    messages: [
      {
        id: 'msg-3-1',
        conversationId: 'conv-3',
        sender: 'buyer',
        content: 'Hi! I love the Scandinavian Table Lamp on your store.',
        timestamp: hoursAgo(1),
      },
      {
        id: 'msg-3-2',
        conversationId: 'conv-3',
        sender: 'buyer',
        content: 'Does this lamp come in white? I only see beige on the listing',
        timestamp: minsAgo(42),
      },
    ],
  },
  {
    id: 'conv-4',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-1',
    storeName: 'TechGear SG',
    externalId: 'tg-103',
    sender: { name: 'Marcus Lim' },
    lastMessage: 'Thanks! Got the tracking number already 👍',
    lastMessageAt: hoursAgo(2),
    isRead: true,
    tags: ['resolved'],
    messages: [
      {
        id: 'msg-4-1',
        conversationId: 'conv-4',
        sender: 'buyer',
        content: 'Hi, can I get the tracking number for my order?',
        timestamp: hoursAgo(4),
      },
      {
        id: 'msg-4-2',
        conversationId: 'conv-4',
        sender: 'ai',
        content: 'Hi Marcus! Your order #TG-88301 is on the way. Tracking: NJ0987654321 via Ninja Van. Estimated delivery: 11–12 May.',
        timestamp: hoursAgo(3),
        aiSuggestion: { text: '', confidence: 'high', autoSent: true },
      },
      {
        id: 'msg-4-3',
        conversationId: 'conv-4',
        sender: 'buyer',
        content: 'Thanks! Got the tracking number already 👍',
        timestamp: hoursAgo(2),
      },
    ],
  },
  {
    id: 'conv-5',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-2',
    storeName: 'HomeDecor MY',
    externalId: 'tg-202',
    sender: { name: 'Siti Rahimah' },
    lastMessage: 'Kalau beli 2 ada diskaun tak?',
    lastMessageAt: hoursAgo(3),
    isRead: true,
    tags: ['pricing'],
    aiSuggestion: {
      text: 'Hai Siti! Untuk pembelian 2 unit ke atas, kami bagi diskaun 10%. Harga biasa RM89/unit, kalau beli 2 jadi RM160.20 untuk kedua-duanya. Nak saya tambahkan ke troli untuk you?',
      confidence: 'medium',
      autoSent: false,
    },
    messages: [
      {
        id: 'msg-5-1',
        conversationId: 'conv-5',
        sender: 'buyer',
        content: 'Helo, saya berminat dengan cushion set yang baru tu.',
        timestamp: hoursAgo(5),
      },
      {
        id: 'msg-5-2',
        conversationId: 'conv-5',
        sender: 'buyer',
        content: 'Kalau beli 2 ada diskaun tak?',
        timestamp: hoursAgo(3),
      },
    ],
  },
  {
    id: 'conv-6',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-1',
    storeName: 'TechGear SG',
    externalId: 'tg-104',
    sender: { name: 'David Chen' },
    lastMessage: 'I want to escalate this. This is unacceptable, I\'ve been waiting 2 weeks',
    lastMessageAt: hoursAgo(6),
    isRead: false,
    tags: ['escalated', 'urgent'],
    order: {
      id: 'TG-88102',
      status: 'Processing',
      items: 'Gaming Monitor 27" x1',
      total: 'SGD 599.00',
    },
    messages: [
      {
        id: 'msg-6-1',
        conversationId: 'conv-6',
        sender: 'buyer',
        content: 'I ordered a gaming monitor 14 days ago. Still no update.',
        timestamp: daysAgo(3),
      },
      {
        id: 'msg-6-2',
        conversationId: 'conv-6',
        sender: 'agent',
        content: 'Hi David, I\'m sorry for the delay. Let me check with our warehouse.',
        timestamp: daysAgo(2),
      },
      {
        id: 'msg-6-3',
        conversationId: 'conv-6',
        sender: 'buyer',
        content: 'Still nothing. This is not acceptable.',
        timestamp: daysAgo(1),
      },
      {
        id: 'msg-6-4',
        conversationId: 'conv-6',
        sender: 'buyer',
        content: 'I want to escalate this. This is unacceptable, I\'ve been waiting 2 weeks',
        timestamp: hoursAgo(6),
      },
    ],
  },
  {
    id: 'conv-7',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-2',
    storeName: 'HomeDecor MY',
    externalId: 'tg-203',
    sender: { name: 'Nurul Ain' },
    lastMessage: 'Ok noted, thank you!',
    lastMessageAt: daysAgo(1),
    isRead: true,
    tags: ['resolved'],
    messages: [
      {
        id: 'msg-7-1',
        conversationId: 'conv-7',
        sender: 'buyer',
        content: 'Hi, what is your return policy?',
        timestamp: daysAgo(2),
      },
      {
        id: 'msg-7-2',
        conversationId: 'conv-7',
        sender: 'ai',
        content: 'Hi Nurul! We accept returns within 14 days of delivery for unused items in original packaging. Just message us with your order number and reason. Refunds are processed within 3–5 business days.',
        timestamp: daysAgo(2),
        aiSuggestion: { text: '', confidence: 'high', autoSent: true },
      },
      {
        id: 'msg-7-3',
        conversationId: 'conv-7',
        sender: 'buyer',
        content: 'Ok noted, thank you!',
        timestamp: daysAgo(1),
      },
    ],
  },
  {
    id: 'conv-8',
    organizationId: 'org-1',
    channel: 'telegram',
    storeId: 'store-1',
    storeName: 'TechGear SG',
    externalId: 'tg-105',
    sender: { name: 'Rajan Pillai' },
    lastMessage: 'Is the USB-C hub compatible with M3 MacBook Pro?',
    lastMessageAt: hoursAgo(8),
    isRead: true,
    tags: ['product-query'],
    aiSuggestion: {
      text: 'Hi Rajan! Yes, the 7-in-1 USB-C Hub is fully compatible with the M3 MacBook Pro (2023/2024). It supports up to 100W PD charging, 4K@60Hz HDMI, and USB 3.2 Gen 2. Would you like to add it to your cart?',
      confidence: 'high',
      autoSent: false,
    },
    messages: [
      {
        id: 'msg-8-1',
        conversationId: 'conv-8',
        sender: 'buyer',
        content: 'Is the USB-C hub compatible with M3 MacBook Pro?',
        timestamp: hoursAgo(8),
      },
    ],
  },
]
