import { Conversation, Store } from './types'

const now = new Date()
const minsAgo = (n: number) => new Date(now.getTime() - n * 60 * 1000)

export const mockStores: Store[] = [
  { id: 'store-1', name: 'TechGadgets SG', channel: 'shopee', unreadCount: 0 },
  { id: 'store-2', name: 'StyleHub MY', channel: 'lazada', unreadCount: 0 },
  { id: 'store-3', name: 'HomeLiving Co', channel: 'tiktok_shop', unreadCount: 0 },
  { id: 'store-4', name: 'Support Bot', channel: 'telegram', unreadCount: 0 },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    organizationId: 'org-1',
    channel: 'shopee',
    externalId: 'shopee-10001',
    sender: { name: 'Amirah Hassan' },
    storeName: 'TechGadgets SG',
    storeId: 'store-1',
    lastMessage: 'Hi, when will my order arrive? I placed it 3 days ago.',
    lastMessageAt: minsAgo(5),
    isRead: false,
    status: 'open',
    tags: ['urgent'],
    order: {
      id: '240513-001',
      status: 'Shipped',
      items: 'Wireless Earbuds Pro × 1',
      total: 'S$89.00',
      trackingNumber: 'SPX-SG-882901',
    },
    aiSuggestion: {
      text: "Hi Amirah! Your order #240513-001 has been shipped and is on its way. The tracking number is SPX-SG-882901. Based on current estimates, it should arrive within 1–2 business days. You can track it directly on the Shopee app. Let me know if you need anything else! 😊",
      confidence: 'high',
      autoSent: false,
      dismissed: false,
    },
    messages: [
      {
        id: 'msg-1-1',
        conversationId: 'conv-1',
        sender: 'customer',
        content: 'Hi, when will my order arrive? I placed it 3 days ago.',
        timestamp: minsAgo(5),
      },
    ],
  },
  {
    id: 'conv-2',
    organizationId: 'org-1',
    channel: 'lazada',
    externalId: 'lazada-20002',
    sender: { name: 'Tan Wei Liang' },
    storeName: 'StyleHub MY',
    storeId: 'store-2',
    lastMessage: 'Can I return this? The size is wrong.',
    lastMessageAt: minsAgo(22),
    isRead: false,
    status: 'open',
    tags: [],
    order: {
      id: 'LZ-556123',
      status: 'Delivered',
      items: 'Oversized Hoodie (M) × 1',
      total: 'RM 79.00',
    },
    aiSuggestion: {
      text: "Hi Wei Liang! I'm sorry the size isn't right. We accept returns within 7 days of delivery — just make sure the item is unworn with original tags attached. I'll raise a return request for you now. Could you confirm the size you need and I'll check stock for an exchange?",
      confidence: 'medium',
      autoSent: false,
      dismissed: false,
    },
    messages: [
      {
        id: 'msg-2-1',
        conversationId: 'conv-2',
        sender: 'customer',
        content: 'Hi, I received my order yesterday.',
        timestamp: minsAgo(60),
      },
      {
        id: 'msg-2-2',
        conversationId: 'conv-2',
        sender: 'customer',
        content: 'Can I return this? The size is wrong.',
        timestamp: minsAgo(22),
      },
    ],
  },
  {
    id: 'conv-3',
    organizationId: 'org-1',
    channel: 'tiktok_shop',
    externalId: 'tiktok-30003',
    sender: { name: 'Siti Nurhaliza' },
    storeName: 'HomeLiving Co',
    storeId: 'store-3',
    lastMessage: 'Is this lamp compatible with a Type G plug?',
    lastMessageAt: minsAgo(45),
    isRead: true,
    status: 'open',
    tags: [],
    aiSuggestion: {
      text: "Hi Siti! Yes, the lamp comes with a universal adapter that includes Type G (UK/SG) plug support, so it will work perfectly for you. It also supports 100–240V, so no voltage converter needed. Would you like to go ahead with the order?",
      confidence: 'high',
      autoSent: false,
      dismissed: false,
    },
    messages: [
      {
        id: 'msg-3-1',
        conversationId: 'conv-3',
        sender: 'customer',
        content: 'Love the aesthetic of this lamp!',
        timestamp: minsAgo(90),
      },
      {
        id: 'msg-3-2',
        conversationId: 'conv-3',
        sender: 'customer',
        content: 'Is this lamp compatible with a Type G plug?',
        timestamp: minsAgo(45),
      },
    ],
  },
  {
    id: 'conv-4',
    organizationId: 'org-1',
    channel: 'shopee',
    externalId: 'shopee-10004',
    sender: { name: 'Marcus Lim' },
    storeName: 'TechGadgets SG',
    storeId: 'store-1',
    lastMessage: "Thanks! I'll go ahead and place the order.",
    lastMessageAt: minsAgo(120),
    isRead: true,
    status: 'open',
    assignedTo: 'You',
    tags: [],
    messages: [
      {
        id: 'msg-4-1',
        conversationId: 'conv-4',
        sender: 'customer',
        content: 'Does the power bank work with MacBook?',
        timestamp: minsAgo(180),
      },
      {
        id: 'msg-4-2',
        conversationId: 'conv-4',
        sender: 'ai',
        content: 'Yes! Our 20,000mAh power bank includes a 65W USB-C port that is fully compatible with all MacBook models.',
        timestamp: minsAgo(175),
        aiSuggestion: { text: '', confidence: 'high', autoSent: true, dismissed: false },
      },
      {
        id: 'msg-4-3',
        conversationId: 'conv-4',
        sender: 'customer',
        content: "Thanks! I'll go ahead and place the order.",
        timestamp: minsAgo(120),
      },
    ],
  },
  {
    id: 'conv-5',
    organizationId: 'org-1',
    channel: 'telegram',
    externalId: 'tg-99005',
    sender: { name: 'Priya Devi' },
    storeName: 'Support Bot',
    storeId: 'store-4',
    lastMessage: 'My parcel has been stuck in transit for 5 days.',
    lastMessageAt: minsAgo(200),
    isRead: false,
    status: 'open',
    tags: ['escalated'],
    order: {
      id: 'TG-20048',
      status: 'Shipped',
      items: 'Skincare Bundle × 1',
      total: 'S$128.00',
      trackingNumber: 'SGPOST-91234',
    },
    messages: [
      {
        id: 'msg-5-1',
        conversationId: 'conv-5',
        sender: 'customer',
        content: 'My parcel has been stuck in transit for 5 days.',
        timestamp: minsAgo(200),
      },
    ],
  },
  {
    id: 'conv-6',
    organizationId: 'org-1',
    channel: 'lazada',
    externalId: 'lazada-20006',
    sender: { name: 'Budi Santoso' },
    storeName: 'StyleHub MY',
    storeId: 'store-2',
    lastMessage: 'Berapa harga untuk beli 3 pasang?',
    lastMessageAt: minsAgo(310),
    isRead: true,
    status: 'open',
    tags: [],
    aiSuggestion: {
      text: 'Halo Budi! Untuk pembelian 3 pasang, kami ada promosi bundle — total hanya RM 189 (jimat RM 48). Mahu saya bantu proses pesanan sekarang?',
      confidence: 'medium',
      autoSent: false,
      dismissed: false,
    },
    messages: [
      {
        id: 'msg-6-1',
        conversationId: 'conv-6',
        sender: 'customer',
        content: 'Berapa harga untuk beli 3 pasang?',
        timestamp: minsAgo(310),
      },
    ],
  },
]
